"use strict";

module.exports = {
  async up(queryInterface, Sequelize) {
    return queryInterface.bulkInsert("Items", [
      {
        id_type: 1,
        authorName: "Nicholas Sparks",
        name: "The Notebook",
        image:
          "https://upload.wikimedia.org/wikipedia/vi/8/86/Posternotebook.jpg",
        numberOfVolumes: 1,
        price: 150000,
        description:
          "Một câu chuyện tình yêu đẹp về một cặp vợ chồng trẻ bị chia cắt bởi hoàn cảnh cuộc sống.",
        publicDate: "1996-10-01",
        publicComName: "Warner Books",
        language: "Tiếng Anh",
        quantity: 50,
      },
      {
        id_type: 1,
        authorName: "Jane Austen",
        name: "Pride and Prejudice",
        image:
          "https://m.media-amazon.com/images/M/MV5BMTA1NDQ3NTcyOTNeQTJeQWpwZ15BbWU3MDA0MzA4MzE@._V1_.jpg",
        numberOfVolumes: 1,
        price: 25000,
        description:
          "Một cuốn tiểu thuyết cổ điển khám phá các chủ đề về tình yêu, hôn nhân và những kỳ vọng của xã hội.",
        publicDate: "1813-01-28",
        publicComName: "T. Egerton, Whitehall",
        language: "Tiếng Anh",
        quantity: 50,
      },
      {
        id_type: 1,
        authorName: "Jojo Moyes",
        name: "Me Before You",
        image:
          "https://m.media-amazon.com/images/M/MV5BMTQ2NjE4NDE2NV5BMl5BanBnXkFtZTgwOTcwNDE5NzE@._V1_.jpg",
        numberOfVolumes: 1,
        price: 135000,
        description:
          "Một câu chuyện đầy cảm xúc về mối quan hệ khó có thể xảy ra giữa người chăm sóc và một người đàn ông bị liệt tứ chi.",
        publicDate: "2012-01-05",
        publicComName: "Michael Joseph",
        language: "Tiếng Anh",
        quantity: 50,
      },
      {
        id_type: 1,
        authorName: "Rainbow Rowell",
        name: "Eleanor & Park",
        image:
          "https://m.media-amazon.com/images/I/71CY50T1sML._AC_UF1000,1000_QL80_.jpg",
        numberOfVolumes: 1,
        price: 99000,
        description:
          "Một câu chuyện cảm động về hai thiếu niên yêu nhau bất chấp sự khác biệt.",
        publicDate: "2013-02-26",
        publicComName: "St. Martin's Press",
        language: "Tiếng Anh",
        quantity: 50,
      },
      {
        id_type: 1,
        authorName: "Colleen Hoover",
        name: "It Ends with Us",
        image:
          "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1688011813i/27362503.jpg",
        numberOfVolumes: 1,
        price: 155000,
        description:
          "Một cuốn tiểu thuyết mạnh mẽ và kích thích tư duy về tình yêu, sức mạnh và những lựa chọn khó khăn.",
        publicDate: "2016-08-02",
        publicComName: "Atria Books",
        language: "Tiếng Anh",
        quantity: 50,
      },
      {
        id_type: 1,
        authorName: "Jojo Moyes",
        name: "After You",
        image: "https://images.penguinrandomhouse.com/cover/9780143108863",
        numberOfVolumes: 1,
        price: 140000,
        description:
          "Phần tiếp theo của cuốn Me Before You, với những câu chuyện mới và sự phát triển của nhân vật sau cái chết đau lòng.",
        publicDate: "2015-09-29",
        publicComName: "Pamela Dorman Books",
        language: "Tiếng Anh",
        quantity: 50,
      },
      {
        id_type: 1,
        authorName: "Rainbow Rowell",
        name: "Fangirl",
        image: "https://mpd-biblio-covers.imgix.net/9781250073808.jpg",
        numberOfVolumes: 1,
        price: 105000,
        description:
          "Câu chuyện về một cô gái trẻ yêu thích viết truyện fanfiction và cuộc sống đầy thách thức của cô trong đại học.",
        publicDate: "2013-09-10",
        publicComName: "St. Martin's Griffin",
        language: "Tiếng Anh",
        quantity: 50,
      },
      {
        id_type: 1,
        authorName: "Graeme Simsion",
        name: "The Rosie Project",
        image:
          "https://upload.wikimedia.org/wikipedia/en/5/53/The_Rosie_Project.jpg",
        numberOfVolumes: 1,
        price: 125000,
        description:
          "Một câu chuyện hài hước và đáng yêu về một nhà khoa học bất ngờ yêu một phụ nữ ngọt ngào và bí ẩn.",
        publicDate: "2013-01-30",
        publicComName: "Text Publishing",
        language: "Tiếng Anh",
        quantity: 50,
      },
      {
        id_type: 1,
        authorName: "Sally Rooney",
        name: "Normal People",
        image: "https://cdn-amz.woka.io/images/I/812dWt7LgdL.jpg",
        numberOfVolumes: 1,
        price: 165000,
        description:
          "Một câu chuyện tình đầy phức tạp và sâu sắc về hai người bạn trẻ và mối quan hệ của họ qua những thăng trầm.",
        publicDate: "2018-08-28",
        publicComName: "Hogarth Press",
        language: "Tiếng Anh",
        quantity: 50,
      },
      {
        id_type: 1,
        authorName: "Jenny Han",
        name: "To All the Boys I've Loved Before",
        image:
          "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1372086100i/15749186.jpg",
        numberOfVolumes: 1,
        price: 95000,
        description:
          "Câu chuyện vui nhộn và ngọt ngào về một cô gái với những lá thư tình bí mật được gửi đến các bạn trai trong quá khứ của cô.",
        publicDate: "2014-04-15",
        publicComName: "Simon & Schuster",
        language: "Tiếng Anh",
        quantity: 50,
      },
      {
        id_type: 2,
        authorName: "Frank Herbert",
        name: "Dune",
        image:
          "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1555447414i/44767458.jpg",
        numberOfVolumes: 1,
        price: 200000,
        description:
          "Một cuộc phiêu lưu không gian kỳ diệu trên sa mạc Địa Cầu, nơi những cuộc đấu tranh chính trị và tôn giáo diễn ra.",
        publicDate: "1965-08-01",
        publicComName: "Chilton Books",
        language: "Tiếng Anh",
        quantity: 50,
      },
      {
        id_type: 2,
        authorName: "Isaac Asimov",
        name: "Foundation",
        image: "https://m.media-amazon.com/images/I/41TZKBUS7PL.jpg",
        numberOfVolumes: 1,
        price: 180000,
        description:
          "Bộ tiểu thuyết khoa học viễn tưởng tương lai, mở đầu cho chuỗi sự kiện kéo dài hàng ngàn năm trong vũ trụ.",
        publicDate: "1951-05-01",
        publicComName: "Gnome Press",
        language: "Tiếng Anh",
        quantity: 50,
      },
      {
        id_type: 2,
        authorName: "Philip K. Dick",
        name: "Do Androids Dream of Electric Sheep?",
        image:
          "https://m.media-amazon.com/images/I/71uN5sUHXiL._AC_UF894,1000_QL80_.jpg",
        numberOfVolumes: 1,
        price: 150000,
        description:
          "Một câu chuyện tương lai đen tối, nơi con người và robot khó phân biệt, đặc biệt là khi mục đích của họ gắn liền với nhau.",
        publicDate: "1968-07-01",
        publicComName: "Doubleday",
        language: "Tiếng Anh",
        quantity: 50,
      },
      {
        id_type: 2,
        authorName: "Orson Scott Card",
        name: "Ender's Game",
        image:
          "https://static.wikia.nocookie.net/ansible/images/8/8e/Ender%27sGameCoverMain.jpg/revision/latest?cb=20210904211643",
        numberOfVolumes: 1,
        price: 170000,
        description:
          "Trong tương lai xa, thế giới dựa vào một thiếu niên thiên tài để chiến đấu chống lại một cuộc xâm lược ngoài hành tinh.",
        publicDate: "1985-01-15",
        publicComName: "Tor Books",
        language: "Tiếng Anh",
        quantity: 50,
      },
      {
        id_type: 2,
        authorName: "Margaret Atwood",
        name: "The Handmaid's Tale",
        image:
          "https://m.media-amazon.com/images/I/71mfL5OGNNL._AC_UF894,1000_QL80_.jpg",
        numberOfVolumes: 1,
        price: 160000,
        description:
          "Một bức tranh kinh dị về một tương lai áp bức và phụ nữ bị hạn chế quyền tự do trong một xã hội theo cách mới.",
        publicDate: "1985-06-01",
        publicComName: "McClelland and Stewart",
        language: "Tiếng Anh",
        quantity: 50,
      },
      {
        id_type: 3,
        authorName: "J.K. Rowling",
        name: "Harry Potter",
        image: "https://m.media-amazon.com/images/I/51Ppi-8kISL.jpg",
        numberOfVolumes: 1,
        price: 250000,
        description:
          "Cuốn sách kể về cuộc phiêu lưu của Harry Potter, một cậu bé phù thủy trẻ tuổi, trong thế giới phép thuật đầy sự nguy hiểm và bí ẩn.",
        publicDate: "1997-06-30",
        publicComName: "Bloomsbury Publishing",
        language: "Tiếng Anh",
        quantity: 50,
      },
      {
        id_type: 3,
        authorName: "J.K. Rowling",
        name: "Harry Potter",
        image:
          "https://static.wikia.nocookie.net/harrypotter/images/6/6d/Chamber_of_Secrets_New_UK_Cover.jpg/revision/latest?cb=20170109045927",
        numberOfVolumes: 2,
        price: 250000,
        description:
          "Cuốn sách kể về cuộc phiêu lưu của Harry Potter, một cậu bé phù thủy trẻ tuổi, trong thế giới phép thuật đầy sự nguy hiểm và bí ẩn.",
        publicDate: "1997-06-30",
        publicComName: "Bloomsbury Publishing",
        language: "Tiếng Anh",
        quantity: 50,
      },
      {
        id_type: 3,
        authorName: "J.K. Rowling",
        name: "Harry Potter",
        image:
          "https://bizweb.dktcdn.net/100/326/228/products/harry-potter-and-the-prisoner-of-azkaban-by-j-k-rowling-jpeg.jpg?v=1540630813240",
        numberOfVolumes: 3,
        price: 250000,
        description:
          "Cuốn sách kể về cuộc phiêu lưu của Harry Potter, một cậu bé phù thủy trẻ tuổi, trong thế giới phép thuật đầy sự nguy hiểm và bí ẩn.",
        publicDate: "1997-06-30",
        publicComName: "Bloomsbury Publishing",
        language: "Tiếng Anh",
        quantity: 50,
      },
      {
        id_type: 3,
        authorName: "J.K. Rowling",
        name: "Harry Potter",
        image:
          "https://static.wikia.nocookie.net/harrypotter/images/a/a3/Goblet_of_Fire_New_Cover.jpg/revision/latest?cb=20170109054633",
        numberOfVolumes: 4,
        price: 250000,
        description:
          "Cuốn sách kể về cuộc phiêu lưu của Harry Potter, một cậu bé phù thủy trẻ tuổi, trong thế giới phép thuật đầy sự nguy hiểm và bí ẩn.",
        publicDate: "1997-06-30",
        publicComName: "Bloomsbury Publishing",
        language: "Tiếng Anh",
        quantity: 50,
      },
      {
        id_type: 3,
        authorName: "J.K. Rowling",
        name: "Harry Potter",
        image:
          "https://upload.wikimedia.org/wikipedia/en/7/70/Harry_Potter_and_the_Order_of_the_Phoenix.jpg",
        numberOfVolumes: 5,
        price: 250000,
        description:
          "Cuốn sách kể về cuộc phiêu lưu của Harry Potter, một cậu bé phù thủy trẻ tuổi, trong thế giới phép thuật đầy sự nguy hiểm và bí ẩn.",
        publicDate: "1997-06-30",
        publicComName: "Bloomsbury Publishing",
        language: "Tiếng Anh",
        quantity: 50,
      },
      {
        id_type: 3,
        authorName: "J.K. Rowling",
        name: "Harry Potter Hoàng Tử Lai",
        image: "https://cdn-amz.woka.io/images/I/A1clNOpnpNL.jpg",
        numberOfVolumes: 6,
        price: 250000,
        description:
          "Cuốn sách kể về cuộc phiêu lưu của Harry Potter, một cậu bé phù thủy trẻ tuổi, trong thế giới phép thuật đầy sự nguy hiểm và bí ẩn.",
        publicDate: "1997-06-30",
        publicComName: "Bloomsbury Publishing",
        language: "Tiếng Anh",
        quantity: 50,
      },
      {
        id_type: 3,
        authorName: "J.K. Rowling",
        name: "Harry Potter và Bảo Bối Tử Thần",
        image:
          "https://static.wikia.nocookie.net/harrypotter/images/d/da/Deathly_Hallows_New_Cover.jpg/revision/latest?cb=20170109054859",
        numberOfVolumes: 7,
        price: 250000,
        description:
          "Cuốn sách kể về cuộc phiêu lưu của Harry Potter, một cậu bé phù thủy trẻ tuổi, trong thế giới phép thuật đầy sự nguy hiểm và bí ẩn.",
        publicDate: "1997-06-30",
        publicComName: "Bloomsbury Publishing",
        language: "Tiếng Anh",
        quantity: 50,
      },
      {
        id_type: 3,
        authorName: "Brent Weeks",
        name: "Chiến Binh Bóng Tối",
        image: "link_hinh_anh",
        numberOfVolumes: 3,
        price: 250000,
        description:
          "Sử thi tưởng tượng điện ảnh theo chân Kylar Stern, một chiến binh bóng tối với khả năng giết người nhanh như chớp và sức mạnh thần bí.",
        publicDate: "2008-08-15",
        publicComName: "Orbit Books",
        language: "Tiếng Anh",
        quantity: 50,
      },
      {
        id_type: 3,
        authorName: "Susan Hill",
        name: "Bóng Ma Trong Gương",
        image: "link_hinh_anh",
        numberOfVolumes: 1,
        price: 199000,
        description:
          "Câu chuyện kinh dị về một người phụ nữ gặp phải sự ám ảnh của một bóng ma trong gương, và mọi cố gắng của cô để khám phá sự thật đằng sau sự hiện diện đáng sợ này.",
        publicDate: "1983-03-01",
        publicComName: "Hamish Hamilton",
        language: "Tiếng Anh",
        quantity: 50,
      },
      {
        id_type: 3,
        authorName: "Carlos Ruiz Zafón",
        name: "Thành Phố Mất Tích",
        image: "link_hinh_anh",
        numberOfVolumes: 4,
        price: 188000,
        description:
          "Cuộc hành trình của một nhà văn trẻ và một câu chuyện bí ẩn xoay quanh một thành phố cổ bị lãng quên, nơi những bí mật kinh hoàng chờ đợi khám phá.",
        publicDate: "2001-10-01",
        publicComName: "Planeta Publishing",
        language: "Tiếng Tây Ban Nha",
        quantity: 50,
      },
      {
        id_type: 3,
        authorName: "Diana Gabaldon",
        name: "Vòng Tròn Lửa",
        image: "link_hinh_anh",
        numberOfVolumes: 8,
        price: 178000,
        description:
          "Một cuộc phiêu lưu thú vị của Claire Randall, một y tá thời gian bị rơi vào thế kỷ 18 ở Scotland và khám phá về các hiện tượng.",
        publicDate: "1991-01-01",
        publicComName: "Arrow Books",
        language: "Tiếng Anh",
        quantity: 50,
      },
      {
        id_type: 4,
        authorName: "Yuval Noah Harari",
        name: "Sapiens: Lược sử Loài Người",
        image: "link_hinh_anh",
        numberOfVolumes: 1,
        price: 200000,
        description:
          "Cuốn sách sử thi tiến hóa của con người, từ thời kỳ tiền sử cho đến hiện đại, khám phá và giải thích những cách mà con người đã tạo ra và duy trì các hệ thống xã hội.",
        publicDate: "2011-04-11",
        publicComName: "Vintage Books",
        language: "Tiếng Anh",
        quantity: 50,
      },
      {
        id_type: 4,
        authorName: "Malcolm Gladwell",
        name: "Quản Lý Thời Gian Thông Minh",
        image:
          "https://www.vinabook.com/images/detailed/360/P91838Mquan_ly_thoi_gian_thong_minh.jpg",
        numberOfVolumes: 1,
        price: 190000,
        description:
          "Cuốn sách nghiên cứu về sự thành công và yếu tố quyết định, khám phá cách mà các cá nhân và xã hội tác động lẫn nhau trong việc đạt được mục tiêu và thành công.",
        publicDate: "2000-11-01",
        publicComName: "Back Bay Books",
        language: "Tiếng Anh",
        quantity: 50,
      },
      {
        id_type: 4,
        authorName: "Edward W. Said",
        name: "Orientalism",
        image:
          "https://m.media-amazon.com/images/I/81rkFz0VJ-L._AC_UF1000,1000_QL80_.jpg",
        numberOfVolumes: 1,
        price: 180000,
        description:
          "Cuốn sách phê phán văn hóa và lịch sử của phương Đông, nghiên cứu cách mà phương Tây đã xây dựng và định kiến ​​về các quốc gia và văn hóa này.",
        publicDate: "1978-07-01",
        publicComName: "Vintage Books",
        language: "Tiếng Anh",
        quantity: 50,
      },
      {
        id_type: 4,
        authorName: "Naomi Klein",
        name: "The Shock Doctrine: Bản Chất Khủng Hoảng",
        image:
          "https://salt.tikicdn.com/cache/w1200/media/catalog/product/s/_/s_c_-_ch_ngh_a_t_b_n_th_m_ho__3.jpg",
        numberOfVolumes: 1,
        price: 200000,
        description:
          "Cuốn sách khám phá cách mà chính trị kinh tế và xã hội tận dụng các tình huống khủng hoảng để thực hiện các biện pháp neo-liberal và thay đổi cấu trúc của xã hội.",
        publicDate: "2007-09-01",
        publicComName: "Picador",
        language: "Tiếng Anh",
        quantity: 50,
      },
      {
        id_type: 4,
        authorName: "Robert Putnam",
        name: "Bowling Alone: America's Declining Social Capital",
        image:
          "https://m.media-amazon.com/images/I/71mpOLYTQML._AC_UF1000,1000_QL80_.jpg",
        numberOfVolumes: 1,
        price: 150000,
        description:
          "Cuốn sách khám phá việc suy giảm của vốn xã hội và các mạng lưới xã hội trong xã hội Mỹ, và những tác động tiêu cực của sự cô lập cá nhân lên cộng đồng.",
        publicDate: "2000-08-01",
        publicComName: "Simon & Schuster",
        language: "Tiếng Anh",
        quantity: 50,
      },
      {
        id_type: 5,
        authorName: "Roald Dahl",
        name: "Charlie và nhà máy sô cô la",
        image:
          "https://upload.wikimedia.org/wikipedia/vi/f/fc/Charlie_v%C3%A0_Nh%C3%A0_M%C3%A1y_S%C3%B4c%C3%B4la_Kim_%C4%90%E1%BB%93ng_60.jpg",
        numberOfVolumes: 1,
        price: 25000,
        description:
          "Cuốn sách kể về cuộc phiêu lưu của Charlie Bucket trong việc khám phá nhà máy sô cô la bí mật của nhà sản xuất sô cô la nổi tiếng Willy Wonka.",
        publicDate: "1964-01-01",
        publicComName: "Puffin Books",
        language: "Tiếng Anh",
        quantity: 50,
      },
      {
        id_type: 5,
        authorName: "Jeff Kinney",
        name: "Nhật ký tiểu thuyết gia Wimpy Kid",
        image:
          "https://upload.wikimedia.org/wikipedia/vi/0/09/Diary_of_a_wimpy_kid.jpg",
        numberOfVolumes: 1,
        price: 135000,
        description:
          "Loạt sách dựa trên nhật ký của Greg Heffley, một học sinh trung học tầm thường ghi lại cuộc sống hàng ngày của mình qua từng câu chuyện hài hước.",
        publicDate: "2007-01-01",
        publicComName: "Amulet Books",
        language: "Tiếng Anh",
        quantity: 50,
      },
      {
        id_type: 5,
        authorName: "Enid Blyton",
        name: "Thám tử Năm Đỏ",
        image:
          "https://salt.tikicdn.com/cache/w1200/ts/product/eb/59/60/5af29425f464c386ca8687304daaa9ff.jpg",
        numberOfVolumes: 1,
        price: 95000,
        description:
          "Câu chuyện kể về nhóm Thám tử Năm Đỏ, gồm năm bạn trẻ, giải quyết các bí ẩn và hiện tượng kỳ lạ xảy ra xung quanh họ.",
        publicDate: "1950-01-01",
        publicComName: "Egmont Books",
        language: "Tiếng Anh",
        quantity: 50,
      },
      {
        id_type: 5,
        authorName: "Marc Brown",
        name: "Arthur's Christmas",
        image:
          "https://images.moviesanywhere.com/c804b194912f55a6a4905111dc9569c6/a12fa0d3-d0d0-41a6-b321-1d297e56be7f.jpg",
        numberOfVolumes: 1,
        price: 75000,
        description:
          "Cuốn sách kể câu chuyện về Arthur Read và những trải nghiệm thú vị của anh ta trong kỳ nghỉ Giáng sinh.",
        publicDate: "1984-08-10",
        publicComName: "Little, Brown Books for Young Readers",
        language: "Tiếng Anh",
        quantity: 50,
      },
      {
        id_type: 5,
        authorName: "Nguyễn Nhật Ánh",
        name: "Cho tôi xin một vé đi tuổi thơ",
        image:
          "https://upload.wikimedia.org/wikipedia/vi/thumb/c/c9/Cho_t%C3%B4i_xin_m%E1%BB%99t_v%C3%A9_%C4%91i_tu%E1%BB%95i_th%C6%A1.jpg/220px-Cho_t%C3%B4i_xin_m%E1%BB%99t_v%C3%A9_%C4%91i_tu%E1%BB%95i_th%C6%A1.jpg",
        numberOfVolumes: 1,
        price: 95000,
        description:
          "Cuốn sách tái hiện hồi ức tuổi thơ đáng nhớ của tác giả qua các câu chuyện, ký ức đầy cảm xúc.",
        publicDate: "2005-01-01",
        publicComName: "Nhã Nam",
        language: "Tiếng Việt",
        quantity: 50,
      },
      {
        id_type: 5,
        authorName: "Hà Thanh Xuân",
        name: "Đường dẫn tới trái tim",
        image:
          "https://salt.tikicdn.com/cache/w1200/media/catalog/product/d/u/duong-den-trai-tim-b.jpg",
        numberOfVolumes: 1,
        price: 69000,
        description:
          "Tiểu thuyết tình cảm lãng mạn kể về câu chuyện tình yêu đầy cảm động và khó khăn giữa hai người.",
        publicDate: "2017-09-20",
        publicComName: "Văn Học",
        language: "Tiếng Việt",
        quantity: 50,
      },
      {
        id_type: 5,
        authorName: "Ngô Thị Thu Hiền",
        name: "Em là của anh",
        image:
          "https://www.dtv-ebook.com/images/files_2/2020/em-la-tieu-tien-nu-cua-anh-ma-ma.jpg",
        numberOfVolumes: 1,
        price: 75000,
        description:
          "Cuốn sách tình cảm ngọt ngào theo chân nhân vật chính trong cuộc tìm kiếm và gặp gỡ tình yêu đích thực của mình.",
        publicDate: "2019-11-10",
        publicComName: "NXB Trẻ",
        language: "Tiếng Việt",
        quantity: 50,
      },
      {
        id_type: 6,
        authorName: "Masashi Kishimoto",
        name: "Naruto",
        image:
          "https://product.hstatic.net/200000343865/product/1_cee005f9445e4f0cb6ce022836687b29_master.jpg",
        numberOfVolumes: 1,
        price: 24000,
        description:
          "Câu chuyện về Naruto Uzumaki, một ninja trẻ tuổi đầy nhiệt huyết, trong hành trình trở thành Hokage – người lãnh đạo mạnh nhất của làng Ninja.",
        publicDate: "1999-09-01",
        publicComName: "Kim Đồng",
        language: "Tiếng Việt",
        quantity: 50,
      },
      {
        id_type: 6,
        authorName: "Masashi Kishimoto",
        name: "Naruto",
        image:
          "https://cdn0.fahasa.com/media/catalog/product/8/9/8935244866070.jpg",
        numberOfVolumes: 2,
        price: 24000,
        description:
          "Câu chuyện về Naruto Uzumaki, một ninja trẻ tuổi đầy nhiệt huyết, trong hành trình trở thành Hokage – người lãnh đạo mạnh nhất của làng Ninja.",
        publicDate: "1999-09-01",
        publicComName: "Kim Đồng",
        language: "Tiếng Việt",
        quantity: 50,
      },
      {
        id_type: 6,
        authorName: "Masashi Kishimoto",
        name: "Naruto",
        image:
          "https://product.hstatic.net/200000343865/product/3_dfbf25d2374747e09b6ea9eb66fdc383_master.jpg",
        numberOfVolumes: 3,
        price: 24000,
        description:
          "Câu chuyện về Naruto Uzumaki, một ninja trẻ tuổi đầy nhiệt huyết, trong hành trình trở thành Hokage – người lãnh đạo mạnh nhất của làng Ninja.",
        publicDate: "1999-09-01",
        publicComName: "Kim Đồng",
        language: "Tiếng Việt",
        quantity: 50,
      },
      {
        id_type: 6,
        authorName: "Masashi Kishimoto",
        name: "Naruto",
        image:
          "https://product.hstatic.net/200000343865/product/4_a6ad7162bf3e490490ea16451271f224_master.jpg",
        numberOfVolumes: 4,
        price: 24000,
        description:
          "Câu chuyện về Naruto Uzumaki, một ninja trẻ tuổi đầy nhiệt huyết, trong hành trình trở thành Hokage – người lãnh đạo mạnh nhất của làng Ninja.",
        publicDate: "1999-09-01",
        publicComName: "Kim Đồng",
        language: "Tiếng Việt",
        quantity: 50,
      },
      {
        id_type: 6,
        authorName: "Masashi Kishimoto",
        name: "Naruto",
        image:
          "https://product.hstatic.net/200000343865/product/5_876a56255f51488cb31a2536b3e939e4_master.jpg",
        numberOfVolumes: 5,
        price: 24000,
        description:
          "Câu chuyện về Naruto Uzumaki, một ninja trẻ tuổi đầy nhiệt huyết, trong hành trình trở thành Hokage – người lãnh đạo mạnh nhất của làng Ninja.",
        publicDate: "1999-09-01",
        publicComName: "Kim Đồng",
        language: "Tiếng Việt",
        quantity: 50,
      },
      {
        id_type: 6,
        authorName: "Masashi Kishimoto",
        name: "Naruto",
        image:
          "https://product.hstatic.net/200000343865/product/6_d65f40f09e8f4b55ac75e5e9f21cc668_master.jpg",
        numberOfVolumes: 6,
        price: 24000,
        description:
          "Câu chuyện về Naruto Uzumaki, một ninja trẻ tuổi đầy nhiệt huyết, trong hành trình trở thành Hokage – người lãnh đạo mạnh nhất của làng Ninja.",
        publicDate: "1999-09-01",
        publicComName: "Kim Đồng",
        language: "Tiếng Việt",
        quantity: 50,
      },
      {
        id_type: 6,
        authorName: "Masashi Kishimoto",
        name: "Naruto",
        image:
          "https://product.hstatic.net/200000343865/product/7_d21928fafac94e51bfc782d350f95667_master.jpg",
        numberOfVolumes: 7,
        price: 24000,
        description:
          "Câu chuyện về Naruto Uzumaki, một ninja trẻ tuổi đầy nhiệt huyết, trong hành trình trở thành Hokage – người lãnh đạo mạnh nhất của làng Ninja.",
        publicDate: "1999-09-01",
        publicComName: "Kim Đồng",
        language: "Tiếng Việt",
        quantity: 50,
      },
      {
        id_type: 6,
        authorName: "Masashi Kishimoto",
        name: "Naruto",
        image:
          "https://product.hstatic.net/200000343865/product/8_3a2c21c976484c7eba122414a95ddc41_master.jpg",
        numberOfVolumes: 8,
        price: 24000,
        description:
          "Câu chuyện về Naruto Uzumaki, một ninja trẻ tuổi đầy nhiệt huyết, trong hành trình trở thành Hokage – người lãnh đạo mạnh nhất của làng Ninja.",
        publicDate: "1999-09-01",
        publicComName: "Kim Đồng",
        language: "Tiếng Việt",
        quantity: 50,
      },
      {
        id_type: 6,
        authorName: "Masashi Kishimoto",
        name: "Naruto",
        image:
          "https://product.hstatic.net/200000343865/product/9_ee14cec4b66743f0830ccb77de0b511b_master.jpg",
        numberOfVolumes: 9,
        price: 24000,
        description:
          "Câu chuyện về Naruto Uzumaki, một ninja trẻ tuổi đầy nhiệt huyết, trong hành trình trở thành Hokage – người lãnh đạo mạnh nhất của làng Ninja.",
        publicDate: "1999-09-01",
        publicComName: "Kim Đồng",
        language: "Tiếng Việt",
        quantity: 50,
      },
      {
        id_type: 6,
        authorName: "Masashi Kishimoto",
        name: "Naruto",
        image:
          "https://product.hstatic.net/200000343865/product/10_2ed5949756af4d64af3dd67b7647760c_master.jpg",
        numberOfVolumes: 10,
        price: 24000,
        description:
          "Câu chuyện về Naruto Uzumaki, một ninja trẻ tuổi đầy nhiệt huyết, trong hành trình trở thành Hokage – người lãnh đạo mạnh nhất của làng Ninja.",
        publicDate: "1999-09-01",
        publicComName: "Kim Đồng",
        language: "Tiếng Việt",
        quantity: 50,
      },
      {
        id_type: 6,
        authorName: "Eiichiro Oda",
        name: "One Piece",
        image:
          "https://product.hstatic.net/200000343865/product/1_cd3e91d598a942589a0c7cc6fde58b0b_master.jpg",
        numberOfVolumes: 1,
        price: 26000,
        description:
          "Cuộc phiêu lưu của Monkey D. Luffy và băng hải tặc Mũ Rơm trong viễn cảnh thế giới biển khơi, tìm kiếm kho báu One Piece để trở thành Vua Hải Tặc.",
        publicDate: "1997-07-15",
        publicComName: "Kim Đồng",
        language: "Tiếng Việt",
        quantity: 50,
      },
      {
        id_type: 6,
        authorName: "Eiichiro Oda",
        name: "One Piece",
        image:
          "https://product.hstatic.net/200000343865/product/2_7c49f80cdc1c48b9a483d9d66fd684c4_master.jpg",
        numberOfVolumes: 2,
        price: 26000,
        description:
          "Cuộc phiêu lưu của Monkey D. Luffy và băng hải tặc Mũ Rơm trong viễn cảnh thế giới biển khơi, tìm kiếm kho báu One Piece để trở thành Vua Hải Tặc.",
        publicDate: "1997-07-15",
        publicComName: "Kim Đồng",
        language: "Tiếng Việt",
        quantity: 50,
      },
      {
        id_type: 6,
        authorName: "Eiichiro Oda",
        name: "One Piece",
        image:
          "https://product.hstatic.net/200000343865/product/3_912467d61ee04b30a50deadf25e82bf4_master.jpg",
        numberOfVolumes: 3,
        price: 26000,
        description:
          "Cuộc phiêu lưu của Monkey D. Luffy và băng hải tặc Mũ Rơm trong viễn cảnh thế giới biển khơi, tìm kiếm kho báu One Piece để trở thành Vua Hải Tặc.",
        publicDate: "1997-07-15",
        publicComName: "Kim Đồng",
        language: "Tiếng Việt",
        quantity: 50,
      },
      {
        id_type: 6,
        authorName: "Eiichiro Oda",
        name: "One Piece",
        image:
          "https://product.hstatic.net/200000343865/product/4_2ec81a14202a4aeaba89708a0f3a74cd_master.jpg",
        numberOfVolumes: 4,
        price: 26000,
        description:
          "Cuộc phiêu lưu của Monkey D. Luffy và băng hải tặc Mũ Rơm trong viễn cảnh thế giới biển khơi, tìm kiếm kho báu One Piece để trở thành Vua Hải Tặc.",
        publicDate: "1997-07-15",
        publicComName: "Kim Đồng",
        language: "Tiếng Việt",
        quantity: 50,
      },
      {
        id_type: 6,
        authorName: "Eiichiro Oda",
        name: "One Piece",
        image:
          "https://bizweb.dktcdn.net/thumb/large/100/386/441/products/5-89.jpg?v=1594705946187",
        numberOfVolumes: 5,
        price: 26000,
        description:
          "Cuộc phiêu lưu của Monkey D. Luffy và băng hải tặc Mũ Rơm trong viễn cảnh thế giới biển khơi, tìm kiếm kho báu One Piece để trở thành Vua Hải Tặc.",
        publicDate: "1997-07-15",
        publicComName: "Kim Đồng",
        language: "Tiếng Việt",
        quantity: 50,
      },
      {
        id_type: 6,
        authorName: "Eiichiro Oda",
        name: "One Piece",
        image:
          "https://bizweb.dktcdn.net/thumb/large/100/386/441/products/6-23.jpg?v=1594705947123",
        numberOfVolumes: 6,
        price: 26000,
        description:
          "Cuộc phiêu lưu của Monkey D. Luffy và băng hải tặc Mũ Rơm trong viễn cảnh thế giới biển khơi, tìm kiếm kho báu One Piece để trở thành Vua Hải Tặc.",
        publicDate: "1997-07-15",
        publicComName: "Kim Đồng",
        language: "Tiếng Việt",
        quantity: 50,
      },
      {
        id_type: 6,
        authorName: "Eiichiro Oda",
        name: "One Piece",
        image:
          "https://bizweb.dktcdn.net/thumb/large/100/386/441/products/7-39.jpg?v=1594705948167",
        numberOfVolumes: 7,
        price: 26000,
        description:
          "Cuộc phiêu lưu của Monkey D. Luffy và băng hải tặc Mũ Rơm trong viễn cảnh thế giới biển khơi, tìm kiếm kho báu One Piece để trở thành Vua Hải Tặc.",
        publicDate: "1997-07-15",
        publicComName: "Kim Đồng",
        language: "Tiếng Việt",
        quantity: 50,
      },
      {
        id_type: 6,
        authorName: "Eiichiro Oda",
        name: "One Piece",
        image:
          "https://bizweb.dktcdn.net/thumb/large/100/386/441/products/8-8.jpg?v=1594705949967",
        numberOfVolumes: 8,
        price: 26000,
        description:
          "Cuộc phiêu lưu của Monkey D. Luffy và băng hải tặc Mũ Rơm trong viễn cảnh thế giới biển khơi, tìm kiếm kho báu One Piece để trở thành Vua Hải Tặc.",
        publicDate: "1997-07-15",
        publicComName: "Kim Đồng",
        language: "Tiếng Việt",
        quantity: 50,
      },
      {
        id_type: 6,
        authorName: "Eiichiro Oda",
        name: "One Piece",
        image:
          "https://bizweb.dktcdn.net/thumb/large/100/386/441/products/9-32.jpg?v=1594705950897",
        numberOfVolumes: 9,
        price: 26000,
        description:
          "Cuộc phiêu lưu của Monkey D. Luffy và băng hải tặc Mũ Rơm trong viễn cảnh thế giới biển khơi, tìm kiếm kho báu One Piece để trở thành Vua Hải Tặc.",
        publicDate: "1997-07-15",
        publicComName: "Kim Đồng",
        language: "Tiếng Việt",
        quantity: 50,
      },
      {
        id_type: 6,
        authorName: "Eiichiro Oda",
        name: "One Piece",
        image:
          "https://bizweb.dktcdn.net/thumb/large/100/386/441/products/10-47.jpg?v=1594705951763",
        numberOfVolumes: 10,
        price: 26000,
        description:
          "Cuộc phiêu lưu của Monkey D. Luffy và băng hải tặc Mũ Rơm trong viễn cảnh thế giới biển khơi, tìm kiếm kho báu One Piece để trở thành Vua Hải Tặc.",
        publicDate: "1997-07-15",
        publicComName: "Kim Đồng",
        language: "Tiếng Việt",
        quantity: 50,
      },
      {
        id_type: 6,
        authorName: "Akira Toriyama",
        name: "Bảy Viên Ngọc Rồng",
        image:
          "https://bizweb.dktcdn.net/thumb/large/100/386/441/products/1-172.jpg?v=1594714163783",
        numberOfVolumes: 1,
        price: 25000,
        description:
          "Cuộc hành trình của Son Goku, một chiến binh Siêu Saiyan, trong việc tìm kiếm các viên ngọc rồng để thực hiện ước muốn của mình.",
        publicDate: "1984-12-15",
        publicComName: "Kim Đồng",
        language: "Tiếng Việt",
        quantity: 50,
      },
      {
        id_type: 6,
        authorName: "Akira Toriyama",
        name: "Bảy Viên Ngọc Rồng",
        image:
          "https://bizweb.dktcdn.net/thumb/large/100/386/441/products/20200714-141617.jpg?v=1594714163783",
        numberOfVolumes: 2,
        price: 25000,
        description:
          "Cuộc hành trình của Son Goku, một chiến binh Siêu Saiyan, trong việc tìm kiếm các viên ngọc rồng để thực hiện ước muốn của mình.",
        publicDate: "1984-12-15",
        publicComName: "Kim Đồng",
        language: "Tiếng Việt",
        quantity: 50,
      },
      {
        id_type: 6,
        authorName: "Akira Toriyama",
        name: "Bảy Viên Ngọc Rồng",
        image:
          "https://bizweb.dktcdn.net/thumb/large/100/386/441/products/3-177.jpg?v=1594714163783",
        numberOfVolumes: 3,
        price: 25000,
        description:
          "Cuộc hành trình của Son Goku, một chiến binh Siêu Saiyan, trong việc tìm kiếm các viên ngọc rồng để thực hiện ước muốn của mình.",
        publicDate: "1984-12-15",
        publicComName: "Kim Đồng",
        language: "Tiếng Việt",
        quantity: 50,
      },
      {
        id_type: 6,
        authorName: "Akira Toriyama",
        name: "Bảy Viên Ngọc Rồng",
        image:
          "https://bizweb.dktcdn.net/thumb/large/100/386/441/products/4-68.jpg?v=1594714163783",
        numberOfVolumes: 4,
        price: 25000,
        description:
          "Cuộc hành trình của Son Goku, một chiến binh Siêu Saiyan, trong việc tìm kiếm các viên ngọc rồng để thực hiện ước muốn của mình.",
        publicDate: "1984-12-15",
        publicComName: "Kim Đồng",
        language: "Tiếng Việt",
        quantity: 50,
      },
      {
        id_type: 6,
        authorName: "Akira Toriyama",
        name: "Bảy Viên Ngọc Rồng",
        image:
          "https://bizweb.dktcdn.net/thumb/large/100/386/441/products/5-67.jpg?v=1594714163783",
        numberOfVolumes: 5,
        price: 25000,
        description:
          "Cuộc hành trình của Son Goku, một chiến binh Siêu Saiyan, trong việc tìm kiếm các viên ngọc rồng để thực hiện ước muốn của mình.",
        publicDate: "1984-12-15",
        publicComName: "Kim Đồng",
        language: "Tiếng Việt",
        quantity: 50,
      },
      {
        id_type: 6,
        authorName: "Akira Toriyama",
        name: "Bảy Viên Ngọc Rồng",
        image:
          "https://bizweb.dktcdn.net/thumb/large/100/386/441/products/6-56.jpg?v=1594714163783",
        numberOfVolumes: 6,
        price: 25000,
        description:
          "Cuộc hành trình của Son Goku, một chiến binh Siêu Saiyan, trong việc tìm kiếm các viên ngọc rồng để thực hiện ước muốn của mình.",
        publicDate: "1984-12-15",
        publicComName: "Kim Đồng",
        language: "Tiếng Việt",
        quantity: 50,
      },
      {
        id_type: 6,
        authorName: "Akira Toriyama",
        name: "Bảy Viên Ngọc Rồng",
        image:
          "https://bizweb.dktcdn.net/thumb/large/100/386/441/products/7-38.jpg?v=1594714163783",
        numberOfVolumes: 7,
        price: 25000,
        description:
          "Cuộc hành trình của Son Goku, một chiến binh Siêu Saiyan, trong việc tìm kiếm các viên ngọc rồng để thực hiện ước muốn của mình.",
        publicDate: "1984-12-15",
        publicComName: "Kim Đồng",
        language: "Tiếng Việt",
        quantity: 50,
      },
      {
        id_type: 6,
        authorName: "Akira Toriyama",
        name: "Bảy Viên Ngọc Rồng",
        image:
          "https://bizweb.dktcdn.net/thumb/large/100/386/441/products/8-51.jpg?v=1594714163783",
        numberOfVolumes: 8,
        price: 25000,
        description:
          "Cuộc hành trình của Son Goku, một chiến binh Siêu Saiyan, trong việc tìm kiếm các viên ngọc rồng để thực hiện ước muốn của mình.",
        publicDate: "1984-12-15",
        publicComName: "Kim Đồng",
        language: "Tiếng Việt",
        quantity: 50,
      },
      {
        id_type: 6,
        authorName: "Akira Toriyama",
        name: "Bảy Viên Ngọc Rồng",
        image:
          "https://bizweb.dktcdn.net/thumb/large/100/386/441/products/9-41.jpg?v=1594714163783",
        numberOfVolumes: 9,
        price: 25000,
        description:
          "Cuộc hành trình của Son Goku, một chiến binh Siêu Saiyan, trong việc tìm kiếm các viên ngọc rồng để thực hiện ước muốn của mình.",
        publicDate: "1984-12-15",
        publicComName: "Kim Đồng",
        language: "Tiếng Việt",
        quantity: 50,
      },
      {
        id_type: 6,
        authorName: "Akira Toriyama",
        name: "Bảy Viên Ngọc Rồng",
        image:
          "https://bizweb.dktcdn.net/thumb/large/100/386/441/products/10-17.jpg?v=1594714163783",
        numberOfVolumes: 10,
        price: 25000,
        description:
          "Cuộc hành trình của Son Goku, một chiến binh Siêu Saiyan, trong việc tìm kiếm các viên ngọc rồng để thực hiện ước muốn của mình.",
        publicDate: "1984-12-15",
        publicComName: "Kim Đồng",
        language: "Tiếng Việt",
        quantity: 50,
      },
      {
        id_type: 6,
        authorName: "Gosho Aoyama",
        name: "Thảm Tử Lừng Danh Conan",
        image:
          "https://bizweb.dktcdn.net/thumb/large/100/386/441/products/11-21.jpg?v=1594633914983",
        numberOfVolumes: 11,
        price: 25000,
        description:
          "Câu chuyện về Shinichi Kudo, một thám tử học sinh trung học, được coi là 'Conan Edogawa' sau khi bị thu nhỏ thành cậu bé.",
        publicDate: "1994-01-01",
        publicComName: "Kim Đồng",
        language: "Tiếng Việt",
        quantity: 50,
      },
      {
        id_type: 6,
        authorName: "Gosho Aoyama",
        name: "Thảm Tử Lừng Danh Conan",
        image:
          "https://bizweb.dktcdn.net/thumb/large/100/386/441/products/12-55.jpg?v=1594633916257",
        numberOfVolumes: 12,
        price: 25000,
        description:
          "Câu chuyện về Shinichi Kudo, một thám tử học sinh trung học, được coi là 'Conan Edogawa' sau khi bị thu nhỏ thành cậu bé.",
        publicDate: "1994-01-01",
        publicComName: "Kim Đồng",
        language: "Tiếng Việt",
        quantity: 50,
      },
      {
        id_type: 6,
        authorName: "Gosho Aoyama",
        name: "Thảm Tử Lừng Danh Conan",
        image:
          "https://bizweb.dktcdn.net/thumb/large/100/386/441/products/13-42.jpg?v=1594633918183",
        numberOfVolumes: 13,
        price: 25000,
        description:
          "Câu chuyện về Shinichi Kudo, một thám tử học sinh trung học, được coi là 'Conan Edogawa' sau khi bị thu nhỏ thành cậu bé.",
        publicDate: "1994-01-01",
        publicComName: "Kim Đồng",
        language: "Tiếng Việt",
        quantity: 50,
      },
      {
        id_type: 6,
        authorName: "Gosho Aoyama",
        name: "Thảm Tử Lừng Danh Conan",
        image:
          "https://bizweb.dktcdn.net/thumb/large/100/386/441/products/anh-bia-4.jpg?v=1594633918827",
        numberOfVolumes: 14,
        price: 25000,
        description:
          "Câu chuyện về Shinichi Kudo, một thám tử học sinh trung học, được coi là 'Conan Edogawa' sau khi bị thu nhỏ thành cậu bé.",
        publicDate: "1994-01-01",
        publicComName: "Kim Đồng",
        language: "Tiếng Việt",
        quantity: 50,
      },
      {
        id_type: 6,
        authorName: "Gosho Aoyama",
        name: "Thảm Tử Lừng Danh Conan",
        image:
          "https://bizweb.dktcdn.net/thumb/large/100/386/441/products/15-45.jpg?v=1594633919790",
        numberOfVolumes: 15,
        price: 25000,
        description:
          "Câu chuyện về Shinichi Kudo, một thám tử học sinh trung học, được coi là 'Conan Edogawa' sau khi bị thu nhỏ thành cậu bé.",
        publicDate: "1994-01-01",
        publicComName: "Kim Đồng",
        language: "Tiếng Việt",
        quantity: 50,
      },
      {
        id_type: 6,
        authorName: "Gosho Aoyama",
        name: "Thảm Tử Lừng Danh Conan",
        image:
          "https://bizweb.dktcdn.net/thumb/large/100/386/441/products/16-8.jpg?v=1594633920590",
        numberOfVolumes: 16,
        price: 25000,
        description:
          "Câu chuyện về Shinichi Kudo, một thám tử học sinh trung học, được coi là 'Conan Edogawa' sau khi bị thu nhỏ thành cậu bé.",
        publicDate: "1994-01-01",
        publicComName: "Kim Đồng",
        language: "Tiếng Việt",
        quantity: 50,
      },
      {
        id_type: 6,
        authorName: "Gosho Aoyama",
        name: "Thảm Tử Lừng Danh Conan",
        image:
          "https://bizweb.dktcdn.net/thumb/large/100/386/441/products/17-21.jpg?v=1594633921007",
        numberOfVolumes: 17,
        price: 25000,
        description:
          "Câu chuyện về Shinichi Kudo, một thám tử học sinh trung học, được coi là 'Conan Edogawa' sau khi bị thu nhỏ thành cậu bé.",
        publicDate: "1994-01-01",
        publicComName: "Kim Đồng",
        language: "Tiếng Việt",
        quantity: 50,
      },
      {
        id_type: 6,
        authorName: "Gosho Aoyama",
        name: "Thảm Tử Lừng Danh Conan",
        image:
          "https://bizweb.dktcdn.net/thumb/large/100/386/441/products/18-42.jpg?v=1594633921960",
        numberOfVolumes: 18,
        price: 25000,
        description:
          "Câu chuyện về Shinichi Kudo, một thám tử học sinh trung học, được coi là 'Conan Edogawa' sau khi bị thu nhỏ thành cậu bé.",
        publicDate: "1994-01-01",
        publicComName: "Kim Đồng",
        language: "Tiếng Việt",
        quantity: 50,
      },
      {
        id_type: 6,
        authorName: "Gosho Aoyama",
        name: "Thảm Tử Lừng Danh Conan",
        image:
          "https://bizweb.dktcdn.net/thumb/large/100/386/441/products/19-31.jpg?v=1594633922893",
        numberOfVolumes: 19,
        price: 25000,
        description:
          "Câu chuyện về Shinichi Kudo, một thám tử học sinh trung học, được coi là 'Conan Edogawa' sau khi bị thu nhỏ thành cậu bé.",
        publicDate: "1994-01-01",
        publicComName: "Kim Đồng",
        language: "Tiếng Việt",
        quantity: 50,
      },
      {
        id_type: 6,
        authorName: "Gosho Aoyama",
        name: "Thảm Tử Lừng Danh Conan",
        image:
          "https://bizweb.dktcdn.net/thumb/large/100/386/441/products/20-33.jpg?v=1594633923763",
        numberOfVolumes: 20,
        price: 25000,
        description:
          "Câu chuyện về Shinichi Kudo, một thám tử học sinh trung học, được coi là 'Conan Edogawa' sau khi bị thu nhỏ thành cậu bé.",
        publicDate: "1994-01-01",
        publicComName: "Kim Đồng",
        language: "Tiếng Việt",
        quantity: 50,
      },
    ]);
  },

  async down(queryInterface, Sequelize) {},
};
